# Generated by Django 3.2.9 on 2021-11-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20211108_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Emp_Id',
            field=models.IntegerField(null=True),
        ),
    ]
