# Generated by Django 3.2.9 on 2021-11-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_employee_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Dept_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='MOb_No',
            field=models.CharField(max_length=20),
        ),
    ]
