# Generated by Django 3.2.9 on 2021-11-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Salary_Month', models.CharField(max_length=30)),
                ('Basic_Salary', models.FloatField()),
                ('TA', models.FloatField()),
                ('DA', models.FloatField()),
                ('PF', models.FloatField()),
                ('Deductions', models.FloatField()),
                ('Convinience', models.FloatField()),
                ('Total_Salary', models.FloatField()),
                ('Net_Salary', models.FloatField()),
                ('Salary_Date', models.DateField()),
            ],
        ),
    ]
